services:
  db:
    image: postgres:15
    environment:
      POSTGRES_DB: vacation_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./vacation_website/VacationProjectGM/init_db.sql:/docker-entrypoint-initdb.d/init_db.sql
    ports:
      - "5433:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5

  vacation_website:
    image: vacation-website:latest
    ports:
      - "8000:8000"
    depends_on:
      db:
        condition: service_healthy
    environment:
      - DEBUG=1
      - DB_HOST=db
      - DB_NAME=vacation_db
      - DB_USER=postgres
      - DB_PASSWORD=password
      - DB_PORT=5432
    volumes:
      - ./vacation_website/VacationProjectGM/media:/app/media
    command: >
      sh -c "python manage.py runserver 0.0.0.0:8000"

  stats_backend:
    image: stats-backend:latest
    ports:
      - "8001:8001"
    depends_on:
      db:
        condition: service_healthy
    environment:
      - DEBUG=1
      - DB_HOST=db
      - DB_NAME=vacation_db
      - DB_USER=postgres
      - DB_PASSWORD=password
      - DB_PORT=5432
    command: >
      sh -c "python manage.py runserver 0.0.0.0:8001"

  stats_frontend:
    image: stats-frontend:latest
    ports:
      - "3000:3000"
    environment:
      - REACT_APP_API_URL=http://localhost:8001/api
    depends_on:
      - stats_backend

volumes:
  postgres_data: